/*
 * Regenerate docs/reading-confluence.md from apps/web/components/Hints.jsx.
 *
 * Hints.jsx claims the in-panel tooltips and the reference doc "cannot
 * disagree" because they share one source. Until this script existed that
 * claim was not enforced by anything — the doc was a hand-mirror, and every
 * HINTS edit was one forgotten paste away from making the claim false.
 *
 *   node scripts/gen_hints_doc.mjs           # write the doc
 *   node scripts/gen_hints_doc.mjs --check   # exit 1 if stale (CI-friendly)
 *
 * No dependencies: HINTS is extracted by evaluating just that object literal,
 * so this runs on a bare node with no build step and no npm install.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const HINTS_PATH = join(root, "apps/web/components/Hints.jsx");
const DOC_PATH = join(root, "docs/reading-confluence.md");

/* ---- extract the HINTS object literal without importing React ---- */
function loadHints() {
  const src = readFileSync(HINTS_PATH, "utf8");
  const start = src.indexOf("export const HINTS = {");
  if (start === -1) throw new Error("HINTS object not found in Hints.jsx");
  const open = src.indexOf("{", start);
  let depth = 0, end = -1;
  for (let i = open; i < src.length; i++) {
    if (src[i] === "{") depth++;
    else if (src[i] === "}") {
      depth--;
      if (depth === 0) { end = i; break; }
    }
  }
  if (end === -1) throw new Error("unbalanced braces in the HINTS literal");
  // eslint-disable-next-line no-new-func
  return new Function(`return ${src.slice(open, end + 1)};`)();
}

const PREAMBLE = `# How to read Confluence

A plain-language guide to every panel on the dashboard. Each section below is the
same explanation that appears in the panel's \u2139 tooltip, plus the context that
does not fit in a tooltip. In-panel hints and this document are generated from one
source (\`components/Hints.jsx\`), so they cannot disagree.

> Generated by \`scripts/gen_hints_doc.mjs\`. Do not edit this file by hand —
> edit the HINTS object in \`apps/web/components/Hints.jsx\` and re-run the script.

## Read the board in this order

The dashboard has a natural top-to-bottom logic. Read it as a funnel:

1. **Market regime** — is today favorable, hostile, or directionless? If it is chop, the honest answer is often *do nothing*, and the rest is context.
2. **VIX + index levels** — the risk backdrop and the specific price rungs that matter.
3. **Tape + options + rotation** — the character of the move, dealer positioning, and where money is rotating. These narrow *where* to look.
4. **Setups** — what the engines composed from all of the above, or the explicit reason there is nothing.
5. **Alerts + journal** — what is live right now, and what the system's ideas have actually done.

## The one thing to keep in mind

Every number on this board traces to a deterministic engine — fractal clusters,
pivot math, GARCH volatility, GEX from option chains. That makes them auditable
facts. It does **not** make them predictions. In definitive backtesting the
composed-setup product underperformed buy-and-hold on every risk-adjusted metric.
So treat this board as *decision support* — a fast, honest read of the tape you
interpret yourself — not as a signal to follow. The confidence score measures how
many engines agree, never a probability of profit.

---
`;

const FOOTER = `
---

*Decision-support tooling, not investment advice. Levels are heuristic pattern
detection; validate with backtests before trading against them.*
`;

function render(hints) {
  const sections = Object.entries(hints).map(([key, h]) => {
    const title = h.title || key;
    const bullets = h.read.map((line) => `- ${line}`).join("\n");
    return `\n## ${title}\n\n*${h.caption}*\n\n**How to read it**\n\n${bullets}\n\n**Caveat** — ${h.caveat}\n`;
  });
  return PREAMBLE + sections.join("") + FOOTER;
}

const hints = loadHints();
const out = render(hints);
const check = process.argv.includes("--check");

if (check) {
  let current = "";
  try { current = readFileSync(DOC_PATH, "utf8"); } catch { /* missing */ }
  if (current !== out) {
    console.error(
      "docs/reading-confluence.md is STALE — run: node scripts/gen_hints_doc.mjs");
    process.exit(1);
  }
  console.log(`docs/reading-confluence.md is current (${Object.keys(hints).length} sections)`);
} else {
  writeFileSync(DOC_PATH, out, "utf8");
  console.log(
    `wrote docs/reading-confluence.md from ${Object.keys(hints).length} HINTS entries`);
}
